name: Keep Alive Job

on:
  schedule:
    - cron: "*/15 * * * *"  # runs every 15 minutes
  workflow_dispatch:        # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios

      - name: Run Keep Alive script
        run: node keep-alive.js
